### ISSUE TITLE
This Framework is awesome! 

### ISSUE THREAD

**Issue by andre991** [hulab/ClusterKit#1]
Hi, firstly congratulation to create this framework, the best of all! I would like to know if you can put the number of pins inside a cluster, just like this one here. Thanks.
![example](https://cloud.githubusercontent.com/assets/8302454/22150869/8e2d21ea-df02-11e6-87fb-7786cd76b868.png)

**Comment by maxep** [comment]
Thanks @andre991 

You are free set any kind of view or image to the cluster. 
If you use MapKit, the delegate method 
`func mapView(_ mapView: MKMapView, viewFor annotation: MKAnnotation) -> MKAnnotationView?` will be called with a cluster as annotation.

If you use GoogleMaps, the data source method 
`mapView(_ mapView: GMSMapView, markerFor cluster: CKCluster) -> GMSMarker` 
for you to provide a cluster marker.

**Comment by andre991** [comment]
OK, Thanks @maxep . I have a problem "/
I using carthage, the cofiguration is correct. 
What's wrong?
<img width="805" alt="captura de tela 2017-01-20 as 16 55 19" src="https://cloud.githubusercontent.com/assets/8302454/22161394/48b2091c-df31-11e6-8535-3fbd98a667ff.png">

**Comment by maxep** [comment]
To use it with MapKit, you need to import `ClusterKit.MapKit`
```swift
import ClusterKit.MapKit
```

**Comment by andre991** [comment]
thanks @maxep, I recommend you put this information in readme because it was not very clear. ;)

**Comment by maxep** [comment]
Will do!
