### ISSUE TITLE
Swift with GoogleMaps doesn't compile

### ISSUE THREAD

**Issue by rujoota** [hulab/ClusterKit#12]
I am trying to work run the example project but it fails with this error:

> dyld: Library not loaded: @rpath/GeoJSONSerialization.framework/GeoJSONSerialization

Also, when I tried setting up my own swift project, I get following compile time error:

> Value of type 'GMSMapView' has no member 'clusterManager'

Here is my podfile:

```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'mapcluster' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mapcluster
  pod 'ClusterKit'
  pod 'GoogleMaps', '~> 2.2'
  pod 'ClusterKit/MapKit'
end
```

**Comment by maxep** [comment]
Have you followed [this](https://github.com/hulab/ClusterKit/wiki/Installation#googlemaps) instructions?

N.B: if you are using GoogleMaps only, you can remove the line `pod 'ClusterKit/MapKit'`

**Comment by rujoota** [comment]
hmm...that fixed issue in my project but example project still doesn't work....

**Comment by rujoota** [comment]
Ok, that works out fine but now it breaks at following error

> GMSMapView clusterManager unrecognized selector sent to instance

**Comment by maxep** [comment]
Did you clean? it's work well on the example.

**Comment by rujoota** [comment]
Turns out I had some problems in bridging-header as well as adding files with specified target. It looks ok now.

Wasn't able to make the example work though.
