### ISSUE TITLE
Inset/Margin

### ISSUE THREAD

**Issue by emadd** [hulab/ClusterKit#14]
Thanks for ClusterKit!  Is it possible to tweak the inset/margins of an "unclustered" marker?  Seems to zoom in a bit too much, particularly when there is only a few markers in the cluster.

![simulator screen shot jul 9 2017 3 26 16 pm](https://user-images.githubusercontent.com/240649/27996923-fcedaa6c-64ba-11e7-8865-9c40ec770378.png)

**Comment by maxep** [comment]
Hi @emadd 
The `GMSCameraUpdate` extension provides methods to zoom with margins:

``` objective-c
+ (GMSCameraUpdate *)fitCluster:(CKCluster *)cluster withPadding:(CGFloat)padding;
+ (GMSCameraUpdate *)fitCluster:(CKCluster *)cluster withEdgeInsets:(UIEdgeInsets)edgeInsets;
```

**Comment by emadd** [comment]
Many thanks
