### ISSUE TITLE
How to get existed annotation by using annotationAtIndex method from CKCluster class ?

### ISSUE THREAD

**Issue by ramanocs1145** [hulab/ClusterKit#15]
Hi Maxep,
Right now I'm working cluster map using this framework(Apple mapkit) on Objective C.
I need to get existed annotations by using  annotationAtIndex from CKCluster class.
Right now I can't access that method using "clusterManager".
If I use "clusterWithCoordinate:" method to access "annotationAtIndex" by using CKCluster instance, but I can't get the existed one because it's initializing newly.

Kindly suggest me.
Thanks.

**Comment by maxep** [comment]
Hi,

I'm not sure to understand, you want to get the annotations of a specific cluster?
You can access all the current clusters for the clusterManager's clusters property. and then access their annotations.

**Comment by ramanocs1145** [comment]
Hi Maxep,

Thanks for your response,

 I have achieved this by getting overall annotations like below and reached my goal this one line.

            NSArray * existedAnnotations = self.mapView.clusterManager.annotations;

Thanks for giving awesome library. It's wonderful ... 👍  
I closed this issue :)
