### ISSUE TITLE
custom annotation class

### ISSUE THREAD

**Issue by HaVaNa77** [hulab/ClusterKit#16]
hi, first of all this extension is great! But for now i 'm not able to get it works:

I have a custom class for annotations, i added CKAnnotation as another issue suggested me, but when i try to add an annotation to cluster: 

self.mapView.clusterManager.annotations = annotation

i get: can not assign value of type MyAnnotation to CKAnnotation.

What's wrong?

here's the code:

` import UIKit
import MapKit
import ClusterKit

class MyAnnotations: NSObject, MKAnnotation, CKAnnotation{
  
    weak public var cluster: CKCluster?

    
    var coordinate: CLLocationCoordinate2D
    var title: String?
    var subtitle: String?
    var name: String?
    var size: String?
    var user: String?
    var owner: String?
    var image: String?
    var latLoc: Double?
    var lonLoc: Double?
    var itemId: String?
    
    init(coordinate: CLLocationCoordinate2D) {
        self.coordinate = coordinate
    }
} `

**Comment by maxep** [comment]
Hi,

`CKAnnotation` inherits from `MKAnnotation`, you just need to use `CKAnnotation`:
```swift
class MyAnnotations: NSObject, CKAnnotation{
    
    weak public var cluster: CKCluster?
    
    var coordinate: CLLocationCoordinate2D
    var title: String?
    var subtitle: String?
    var name: String?
    var size: String?
    var user: String?
    var owner: String?
    var image: String?
    var latLoc: Double?
    var lonLoc: Double?
    var itemId: String?
    
    init(coordinate: CLLocationCoordinate2D) {
        self.coordinate = coordinate
    }
}
```
Then, you have to assign an array of annotation to the cluster manager, not a single one.

**Comment by HaVaNa77** [comment]
Thnx mcaxep, i made an array:
 var newArray:[Annotation] = []
then i add annotations to that array:
self.newArray.append(annotation)

but when i do this i get the same error...

Can you help me?

**Comment by maxep** [comment]
I cannot reproduce your issue in the swift exemple project, I tried with:
```swift
mapView.clusterManager.annotations = [MyAnnotations(coordinate: CLLocationCoordinate2D(latitude: 48.853, longitude: 2.35))]
```

**Comment by HaVaNa77** [comment]
Ok i found the problem ( var newArray:[Annotation] = []) had to be var newArray:[MyAnnotations] 

Thnx!

**Comment by HaVaNa77** [comment]
Sorry  again, i'm quite there but.. in the function:

  ```
func mapView(_ mapView: MKMapView, viewFor annotation: MKAnnotation) -> MKAnnotationView? {
        
        let annotationView = mapView.dequeueReusableAnnotationView(withIdentifier: "annotation") ??
            MKAnnotationView(annotation: annotation, reuseIdentifier: "annotation")
        
        if let cluster = annotation as? CKCluster {
            
            if cluster.count > 1 {
                annotationView.canShowCallout = false
                annotationView.image = UIImage(named: "cluster")
            } else {
             annotationView.canShowCallout = true
             annotationView.image = UIImage(named: "marker")
```
i added: 
           
 let MyAnnotations = annotation as! MyAnnotations
             if MyAnnotations.user == userID {.........


because i've to access MyAnnotation properties but compiler shows me this error:

Could not cast value of type 'NSKVONotifying_CKCluster' (0x608000106540) to 'app.MyAnnotations' (0x1071d61f8).

**Comment by maxep** [comment]
Yes because the annotation parameter is indeed a CKCluster, that cluster represents a group of annotation. These annotations are accessible in the `annotations` property of the cluster.

**Comment by HaVaNa77** [comment]
can you make me a simple example of how can i access them please? I really need to access properties like size that is defined MyAnnotation class, sorry about being stressing but i'm too to understand well your code..
