### ISSUE TITLE
Cluster containing multiple annotations with exact same coordinates.

### ISSUE THREAD

**Issue by ngrichyj4** [hulab/ClusterKit#19]
Currently, when a cluster contains multiple annotations with exact same coordinates, they do not expand (display child annotations) when tapped on or zoomed in. Is there a way to add handle such cases or perhaps add displacement to this annotations so they're displayed separately.

**Comment by maxep** [comment]
You can reduce the `maxZoomLevel` of the cluster manager to have access to the annotations. But they wont be distinct.

**Comment by Alex293** [comment]
+1

Here could be some directions to solve this :
https://stackoverflow.com/questions/44698027/correctly-handle-clustering-when-markers-are-placed-identically-and-overlapping

**Comment by ramanocs1145** [comment]
Hi maxep,
Today I have also faced this kind of issue. After reduce the "maxZoomLevel", I can see the child annotatins.

Thanks for the above solution.
:) 👍

**Comment by alexsteinerde** [comment]
This library handles this quit nice: https://github.com/ashare80/TSClusterMapView
It moves the annotations in a circular form around the center
