### ISSUE TITLE
missing sources in cocoa specs ?

### ISSUE THREAD

**Issue by rgdev** [hulab/ClusterKit#2]
I installed the lib using cocoapods and tried to implement it in a project but I noticed the `clusterManager` property is missing from `MKMapView`.

I looked into the `ClusterKit` folder containing the sources files (inside the `Pods` folder) and only the `Core` folder is here but not the `MapKit` or `GoogleMaps` folders.

I suppose these folder should be present right?

**Comment by maxep** [comment]
Hi @rgdev 
Actually ClusterKit for MapKit is a submodule. In your podfile, use this:
```
pod 'ClusterKit/MapKit'
```

**Comment by rgdev** [comment]
My bad, thank you for the quick reply @maxep.
