### ISSUE TITLE
PCH Error

### ISSUE THREAD

**Issue by AshishPatel48** [hulab/ClusterKit#25]
I am working on swift 4

/Users/mac/Documents/Ashish/Project/Working Project/BitBucket/eventyr-ios-master/<built-in>:1:10: '/Users/mac/Documents/Ashish/Project/Working Project/BitBucket/eventyr-ios-master/eventyr/Application/eventyr-Prefix.pch' file not found

**Comment by maxep** [comment]
This is an issue in your app project, not related to ClusterKit.
