### ISSUE TITLE
clusterManager issue 

### ISSUE THREAD

**Issue by AshishPatel48** [hulab/ClusterKit#26]
Can u plz help, Got error while run app

-[GMSMapView clusterManager]: unrecognized selector sent to instance 0x7f84d108ea00

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[GMSMapView clusterManager]: unrecognized selector sent to instance 0x7f84d108ea00'

**Comment by maxep** [comment]
Please follow the [installation guide for GoogleMaps](https://github.com/hulab/ClusterKit/wiki/Installation#googlemaps).
