### ISSUE TITLE
Show Total Pins

### ISSUE THREAD

**Issue by Rahulgupta-cdnsol** [hulab/ClusterKit#28]
Hi,
I have checked the library but I didn't found how I can put the total number of map PIN covered in the region as compared to other libraries so please let me know if your library provides a way to achieve the same.

Thanks

**Comment by aguilarpgc** [comment]
@Rahulgupta-cdnsol, check this when you subclass the cluster annotation:

>     class CKClusterView: MKAnnotationView {
>     
>     lazy var titulo: UILabel = {
>         
>         let label = UILabel()
>         label.autoresizingMask = [.flexibleWidth, .flexibleHeight]
>         label.adjustsFontSizeToFitWidth = true
>         label.baselineAdjustment = .alignCenters
>         label.font = UIFont.systemFont(ofSize: 10)
>         label.frame = self.bounds
>         label.textAlignment = .center
>         label.textColor = .white
>         self.addSubview(label)
>         
>         return label
>     }()
>     
>     override init(annotation: MKAnnotation?, reuseIdentifier: String?) {
>         super.init(annotation: annotation, reuseIdentifier: reuseIdentifier)
>         
>         backgroundColor = UIColor.darkGray
>         
>         frame = CGRect(origin: frame.origin, size: CGSize(width: 30.0, height: 30.0))
>         
>         layer.cornerRadius = bounds.size.width * 0.5
>         layer.borderColor = UIColor.black.cgColor
>         layer.borderWidth = 3.0
>     }
>     
>     required init?(coder aDecoder: NSCoder) {
>         super.init(coder: aDecoder)
>     }
>     }

**Comment by aguilarpgc** [comment]
@Rahulgupta-cdnsol then in MKMapViewDelegate just assign the count number:
> 
>     func mapView(_ mapView: MKMapView, viewFor annotation: MKAnnotation) -> MKAnnotationView? {
>         guard let cluster = annotation as? CKCluster else {
>             return nil
>         }
>         
>         if cluster.count > 1 {
>             
>             let annotationView: CKClusterView = mapView.dequeueReusableAnnotationView(withIdentifier: CKMapViewDefaultClusterAnnotationViewReuseIdentifier) as? CKClusterView ??
>                 CKClusterView(annotation: annotation, reuseIdentifier: CKMapViewDefaultClusterAnnotationViewReuseIdentifier)
>             
>             annotationView.titulo.text = "\(cluster.count)"
>             
>             return annotationView
>         }
>         else {
>             
>             return mapView.dequeueReusableAnnotationView(withIdentifier: CKMapViewDefaultAnnotationViewReuseIdentifier) ??
>                 CKAnnotationView(annotation: annotation, reuseIdentifier: CKMapViewDefaultAnnotationViewReuseIdentifier)
>         }
>     }

**Comment by aguilarpgc** [comment]
@Rahulgupta-cdnsol and you can get something like this:

![example](https://user-images.githubusercontent.com/3612180/32669854-f5c3f942-c60f-11e7-907f-a7135de830b4.png)

**Comment by maxep** [comment]
Thanks @aguilarpgc for your example
