### ISSUE TITLE
Mapbox integration

### ISSUE THREAD

**Issue by danielerapali** [hulab/ClusterKit#29]
Hi, I have an error to add the pod for mapbox 

[!] Unable to satisfy the following requirements:

- `ClusterKit/Mapbox` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `ClusterKit/Mapbox`.

Can you help me ?

**Comment by maxep** [comment]
did you run `pod repo update`?

**Comment by danielerapali** [comment]
Hi, 
Is the first time that I am using this pod. I used pod install 

Daniele Rapali
iOS Developer

e: daniele@infiniteintel.com
m: +44 (0) 7427 350162

Infinite Intelligence Technologies Limited
8-9 Frith Street, Soho
London W1D 3JB

**Comment by maxep** [comment]
Try to run `pod repo update` before install.
