### ISSUE TITLE
International date line (longitude 180/-180) breaks clustering

### ISSUE THREAD

**Issue by jonaspom** [hulab/ClusterKit#31]
Hi

Great work with the Kit! Integration was easy and it actually works quite fast and reliable unlike the frameworks I have experimented before. However I think I found a special case that's not handled.

When navigating in GoogleMaps so that the view covers the international date line (longitude 180 / -180) all clusters on the map disappear. They reappear immediately when moving completely on either side of the line. Even though this is more of an inconvinience than a real blocker it gives an incomplete user experience and I would love to have this working. See the gif below for an example.

Even with this issue the ClusterKit is great, thank you. :)

![img_8838 trim](https://user-images.githubusercontent.com/15215313/32994607-82a3cab8-cd72-11e7-99c7-ec9bd621b112.gif)

**Comment by MarvinNazari** [comment]
This happens for me as well. The pins just disappears and appears again when u just zoom in or out or move a little bit.

**Comment by maxep** [comment]
Thanks @jonaspom for the report, I should be able to push a fix for the next version.
Mapbox is also struggling with the `visibleCoordinateBounds` crossing the antimeridian: mapbox/mapbox-gl-native#4664, which introduce a weird behavior. I will see if I can find a workaround for Mapbox also.

**Comment by jonaspom** [comment]
Thanks @maxep However, the issue persists with Google Maps and the latest ClusterKit 0.3.3
