### ISSUE TITLE
 [Mapbox] Using ClusterKit with MGLPointAnnotation

### ISSUE THREAD

**Issue by afomich** [hulab/ClusterKit#35]
Hello! Thanks for ClusterKit!

I have a project with tons of MGLPointAnnotation (with custom icons) and etc.
I do not use GeoJSON, all points are added dynamically. I found the way how to utilize ClusterKit with annotationViews, and it works, but I have a duplicates for every PointAnnotation and other problems. 
Is there any simple way to use this kit for MGLPointAnnotations, not for MGLAnnotationView?

**Comment by afomich** [comment]
The main problem is that I encounter such a "Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PointAnnotation count]: unrecognized selector sent to instance 0x1c1069000'" error in - (nullable MGLAnnotationView *)mapView:(MGLMapView *)mapView viewForAnnotation:(id <MGLAnnotation>)annotation

**Comment by afomich** [comment]
@interface PointAnnotation : MGLPointAnnotation

@property (strong, nonatomic) id userInfo;
@property (strong, nonatomic) NSString *type;
@property (strong, nonatomic) NSNumber* marker_id;

@end

**Comment by chinna834** [comment]
Could you please explain your approach for this issue. I have the same issue.
