### ISSUE TITLE
Install/Configure directions incomplete.  

### ISSUE THREAD

**Issue by tekbob27** [hulab/ClusterKit#39]
The Mapbox (and probably google) install directions should include the block of instructions that state that each of the targets is a separate sub package.

**Comment by maxep** [comment]
I'm not sure to understand, you mean in the [wiki](https://github.com/hulab/ClusterKit/wiki) ?

**Comment by tekbob27** [comment]
Yes, in the wiki.  I must have had a cached version that was not updating, as the link you included was clearer. 

Do you have an example of how ClusterKit works with custom annotation views?

Thanks
Bob

**Comment by tekbob27** [comment]
Another issue I have is that I needed to extend/implement MKAnnotation on my custom annotations as the base class used in the annotation management methods is MKAnnotation.  My custom annotations are all MGLAnnotations.
