### ISSUE TITLE
Property 'annotations' not found on object of type 'CKCluster *'

### ISSUE THREAD

**Issue by ghost** [hulab/ClusterKit#4]
Hello, 
I'm trying to implement ClusterKit, 
but can't seem to correct 2 errors, 
first is the title
Looking into CKCluster.h and m, I can't seem to see that either annotations and its getter functions are public
second, the pod subspec for GoogleMaps doesn't seem to be available

**Comment by ghost** [comment]
Ok Solved, 
In your readme 
if (cluster.annotations.count > 1) {
            [mapView showCluster:cluster animated:YES];
        }
should be changed to 
if (cluster.count > 1) {
     [mapView showCluster:cluster animated:YES];
}

**Comment by maxep** [comment]
Thanks, will do.
The podspec for GoogleMaps is not available because GoogleMaps cannot be added as a sub dependancy, you have to add it manually as explain in the [Installation](https://github.com/hulab/ClusterKit#installation).
