### ISSUE TITLE
Unable to use MGLPointAnnotation using ClusterKit

### ISSUE THREAD

**Issue by chinna834** [hulab/ClusterKit#40]
How to customize MGLPointAnnotation class for Mapbox using ClusterKit. Seems like ClusterKit is using MKAnnotation.

**Comment by maxep** [comment]
You need MGLPointAnnotation to comply to `MKAnnotation` protocol:

```objective-c
@interface MGLPointAnnotation (ClusterKit) <MKAnnotation>

@end
```

```swift
extension MGLPointAnnotation: MKAnnotation {
    
}
```
