### ISSUE TITLE
How to: display the number of objects in the cluster on the map

### ISSUE THREAD

**Issue by Belzik** [hulab/ClusterKit#46]
Hey, guys. I would like to thank you for this library. But I have a question. Is it possible to display the number of objects in the cluster next to the cluster icon or inside the cluster icon? I use Mapbox.

**Comment by dvertovsek** [comment]
@Belzik 
[This](https://stackoverflow.com/a/28907826) stackoverflow answer helped me with the same problem :)

You can find the number of annotations in a cluster inside the method `func mapView(_ mapView: MKMapView, viewFor annotation: MKAnnotation) -> MKAnnotationView? `

using:

```
if let ckCluster = annotation as? CKCluster {
          annotationView.image = yourImage.draw("\(ckCluster.count)")
}
```

**Comment by ulaserdegor** [comment]
if let ckCluster = annotation as? CKCluster {
          annotationView.image = yourImage.draw("\(ckCluster.annotations.count)") 
}

give wrong numbers.

**Comment by ulaserdegor** [comment]
> @Belzik
> [This](https://stackoverflow.com/a/28907826) stackoverflow answer helped me with the same problem :)
> 
> You can find the number of annotations in a cluster inside the method `func mapView(_ mapView: MKMapView, viewFor annotation: MKAnnotation) -> MKAnnotationView? `
> 
> using:
> 
> ```
> if let ckCluster = annotation as? CKCluster {
>           annotationView.image = yourImage.draw("\(ckCluster.count)")
> }
> ```

give wrong numbers
