### ISSUE TITLE
Not displaying non-clustered annotations

### ISSUE THREAD

**Issue by dvertovsek** [hulab/ClusterKit#47]
If I choose to exclude an annotation from being clustered using `func clusterManager(_ clusterManager: CKClusterManager, shouldClusterAnnotation annotation: MKAnnotation) -> Bool` then that annotation is not displayed on the map.

Is this intended behaviour?

**Comment by nnhubbard** [comment]
I am having this issue as well and would love to get it fixed!

**Comment by maxep** [comment]
Yes, this is intended. Annotations will be excluded from clusters but not from the map.
If you do not want to display an annotation, you can remove it from the cluster manager: `[CKClusterManager removeAnnotation:]`

**Comment by nnhubbard** [comment]
@maxep But we are not even seeing the annotation on the map when using this method. It is never shown. It is my understanding that the annotation should always be showing on the map, which isn't the case here.
