### ISSUE TITLE
Mapbox 4.0 support 

### ISSUE THREAD

**Issue by alexandremorgado** [hulab/ClusterKit#48]
Hi guys! Do you have plans to support Mapbox version 4.0? ClusterKit is currently dependent of Mapbox 3.6. 

Thank you for this amazing lib!

**Comment by dolzhenko-tony** [comment]
@alexandremorgado here I made pull request for this: https://github.com/hulab/ClusterKit/pull/49
You can use my fork if needed: https://github.com/dolzhenko-tony/ClusterKit

**Comment by nnhubbard** [comment]
Don't use cocoapods and you will be fine.

**Comment by maxep** [comment]
Sorry for the late response.
Mapbox has been updated to 4.6, available in ClusterKit 0.3.5.
