### ISSUE TITLE
Can't implement :(

### ISSUE THREAD

**Issue by yetelday** [hulab/ClusterKit#5]
Hi, I'm trying to implement the library but I'm stuck, I have an array of MKAnnotation for my locations but the cluestermanager expects CKAnnotation objects...

**Comment by andre991** [comment]
You need include the protocol CKAnnotation in your custom annotation.

**Comment by yetelday** [comment]
OK, I didn't create a custom annotation... I just used MKAnotation

**Comment by yetelday** [comment]
I created a class that inherits from MKAnnotationPoint and implements the CKAnnotation protocol and then fill my array and when I try to pass it to the clusterManager I get 
'-[Annotation setCluster:]: unrecognized selector sent to instance'

**Comment by maxep** [comment]
`cluster` is a required property, you should add `@synthesize cluster;` to your implementation.

**Comment by yetelday** [comment]
Thanks ! Got it Working !

**Comment by yetelday** [comment]
just a few questions, how do you animate the elements of the cluster when they merge and separate, and is there a way to have the cluster place itself at the combined center of the elements it clusters ?
Thanks

**Comment by maxep** [comment]
You have several types of cluster: `CKCluster `, `CKCentroidCluster `, `CKNearestCentroidCluster `, `CKBottomCluster`. 

If you want to change the type (`CKCentroidCluster` in your case), you can register it by calling `registerClusterClass:` of the algorithm.
