### ISSUE TITLE
[CKCluster retain]: message sent to deallocated instance

### ISSUE THREAD

**Issue by nnhubbard** [hulab/ClusterKit#65]
I am having an issue in Google Maps, sometimes when the delegate `mapView:didTapMarker:` is called and I access the .cluster property of the marker, I got a message and crash that the message was sent to a deallocated instance:

> [CKCluster retain]: message sent to deallocated instance

Is there any reason why this might be happening and why the object has been deallocated?

**Comment by maxep** [comment]
The `cluster` property of `GMSMarker` is marked as weak but it's actually an `assign`. If you try to access it after the cluster list has changed, the cluster instance will be deallocated. Is there any reason the clusters list would change at this stage? do you have a snippet of your `mapView:didTapMarker:`?

**Comment by nnhubbard** [comment]
I spent too much time trying to debug this issue and couldn't figure it out and needed to move on. I moved to Google Maps Utilities clustering instead.

**Comment by peterlendvay** [comment]
@maxep We are experiencing the same issue, but we are actually changing the cluster list in `mapView:didTapMarker:`. Is there a solution for this? Thanks!
