### ISSUE TITLE
Working with annotations downloaded from server on region change?

### ISSUE THREAD

**Issue by gerchicov-bp** [hulab/ClusterKit#83]
You are perfect! In the example you precreated a local list of points and don't change it. But what if you have an infinite number of points and server sends you a limited annotation info based on the selected region?

**Comment by alexsteinerde** [comment]
You can use the delegate method `func mapView(_: MKMapView, regionDidChangeAnimated _: Bool)` the protocol `MKMapViewDelegate` provides as I understand your question correctly. Inside of the function you can then make the network request to load more pins.

**Comment by maxep** [comment]
Yes, you can request new annotations and use the `CKClusterManager.addAnnotations(_:)`
