### ISSUE TITLE
Value of type 'MGLMapView' has no member 'clusterManager'

### ISSUE THREAD

**Issue by kleeb** [hulab/ClusterKit#84]
I am getting

```
error: value of type 'MGLMapView' has no member 'clusterManager'
            mapView.clusterManager.algorithm = algorithm
```

MGLMapView does not have anything called clusterManager, I also don't see that it was removed in previous versions of Mapbox iOS SDK, nor deprecated. Any ideas?

**Comment by sup8369** [comment]
Change `pod 'ClusterKit'` to `pod 'ClusterKit/Mapbox'`
