### ISSUE TITLE
Doesn't work with swift  

### ISSUE THREAD

**Issue by Zuzic** [hulab/ClusterKit#9]
I use Carthage. I always get error:
'ClusterKit/CKClusterManager.h' file not found

**Comment by maxep** [comment]
Did you add ClusterKit.framework as a embedded binary and did you import the module with `import ClusterKit.MapKit` ?

**Comment by Zuzic** [comment]
Yes

**Comment by maxep** [comment]
Well it's working on my side. Without an explicit description of your issue, I couldn't help..

**Comment by Zuzic** [comment]
Thanks
